### ISSUE TITLE
Can Unity Search window be supported?

### ISSUE THREAD

**Issue by eai04191** [hai-vr/animation-viewer-vcc#2]
https://docs.unity3d.com/Manual/search-overview.html

The Search window supports more advanced searches and larger thumbnails than the Project window, so it would be useful to see animation thumbnails here.

**Comment by hai-vr** [comment]
WIP

![Unity_rgAztbJlc7](https://github.com/user-attachments/assets/83d1647c-6142-4da8-9135-c3e16a2105da)

**Comment by hai-vr** [comment]
Planned for V2.1.0
- f3baf929586546ebe45e2d16e0d85edeaae5c57a afaec7841af8e288a8b8c5c5d5d01853a14ed98f b50a8b4c02da3b7fc9e37d8a648e4863a417f826
